apiVersion: apps/v1
kind: Deployment
metadata:
  name: testcat2
  namespace: testcat2
  labels:
    app: testcat2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testcat2
  template:
    metadata:
      labels:
        app: testcat2
    spec:
      containers:
        - name: testcat2
          image: europe-west1-docker.pkg.dev/labo-quentin/apps/testcat2-code@sha256:5d87896e7a8f4ea4a5159977331a08b178a09be1f1ce63dbff9cf596cf412d3c
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
