apiVersion: apps/v1
kind: Deployment
metadata:
  name: testcat4
  namespace: testcat4
  labels:
    app: testcat4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testcat4
  template:
    metadata:
      labels:
        app: testcat4
    spec:
      containers:
        - name: testcat4
          image: europe-west1-docker.pkg.dev/labo-quentin/apps/testcat4-code@sha256:edfad6131116cff658f0948bd6b2c5aa56af336d5c6a1459b782ada88561f081
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
