apiVersion: v1
kind: Service
metadata:
  name: e2e-p1-0916112434
  namespace: e2e-p1-0916112434
spec:
  selector:
    app: e2e-p1-0916112434
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
