apiVersion: v1
kind: Service
metadata:
  name: e2e-p1-0916192801
  namespace: e2e-p1-0916192801
spec:
  selector:
    app: e2e-p1-0916192801
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
